### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bhagen55** [honzasp/rust-turbojpeg#11]
Hi,
Could I potentially convince you to convert the licensing of this Crate/project to a more defined license perhaps [MIT](https://opensource.org/license/mit/)? There are some [issues with "unlicensed" software](https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense) that can make life a bit difficult.
I specifically would like to use it in code I am writing for my job, so I realize asking for the license to be changed so a corporation can use your work for free is probably a bit annoying, but I figured I'd try asking anyways :slightly_smiling_face: .

**Comment by honzasp** [comment]
Hi, I'm willing to perform any legal rituals that would help you use the library! :) I would like to keep the library in the public domain, but I can dual-license it under MIT. Do you have some specific arrangement that would work for your job?

**Comment by bhagen55** [comment]
I don't have anything specific other than using a general open source license, like MIP or Apache-2.0. Dual licensing is fine!

Yes I do work for Zipline!

**Comment by honzasp** [comment]
I added an MIT license in this commit on the `mit` branch: https://github.com/honzasp/rust-turbojpeg/commit/7ce56ede68fc2c40e04e4d1a01d5ffc20ef0052b

Could you please have a look, whether this would work for you? If so, I will merge this and release a new version to crates.io.

I really like what you are doing at Zipline, and I'm glad that my little library can help you :)

**Comment by bhagen55** [comment]
That is perfect! Thank you very much.

**Comment by honzasp** [comment]
Good, I merged the changes and released version 0.5.3 to crates.io. I hope that the library will be useful to you!

**Comment by micolous** [comment]
Hi, I don't think this is fully fixed: `turbojpeg-sys` still declares it is `UNLICENSE` only:

https://github.com/honzasp/rust-turbojpeg/blob/abbc5567d59220cb7ba0cf88c334bdadfa50c258/turbojpeg-sys/Cargo.toml#L10

Thanks!

**Comment by honzasp** [comment]
This is going to be fixed in version 1.0.0 (I just released a pre-release 1.0.0-pre.0)
