### ISSUE TITLE
Decode to YUV

### ISSUE THREAD

**Issue by devguy22** [honzasp/rust-turbojpeg#12]
I've been trying out this library, and I was wondering how I can make it decode my (already YUV encoded) JPEG images straight into a YUV planar image (ideally 420)? I see mention of it in the comments, and turbojpeg itself should be able to do this, but I cannot set an output pixel format of YUV (or ycbcr or however you want to refer to it as).

**Comment by honzasp** [comment]
Hi, TurboJPEG does support decoding into YUV planes, but this functionality is not yet exposed by this library in Rust. I will see how hard it would be to add it.

**Comment by devguy22** [comment]
Hey, I have something kind of working from modifying this library. If you haven't already started on this, I might be able to have a PR in a few days.

**Comment by darioalessandro** [comment]
@devguy22 !!! cut them transforms!
