### ISSUE TITLE
Error when cross-compiling for `x86_64-pc-windows-gnu`

### ISSUE THREAD

**Issue by balins** [honzasp/rust-turbojpeg#21]
Hi, I've been using this crate and everything has been fine until I had to compile for `x86_64-pc-windows-gnu` target on macOS/Ubuntu:

To reproduce on macOS, in `turbojpeg-sys` run:
```
> cargo build --release --target x86_64-pc-windows-gnu --verbose
[...]
Running `/Users/balins/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc --crate-name turbojpeg_sys --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="cmake"' --cfg 'feature="default"' --cfg 'feature="pkg-config"' --cfg 'feature="require-simd"' -C metadata=f7c1202d12eefe92 -C extra-filename=-f7c1202d12eefe92 --out-dir /Users/balins/rust-turbojpeg/turbojpeg-sys/target/x86_64-pc-windows-gnu/release/deps --target x86_64-pc-windows-gnu -C strip=debuginfo -L dependency=/Users/balins/rust-turbojpeg/turbojpeg-sys/target/x86_64-pc-windows-gnu/release/deps -L dependency=/Users/balins/rust-turbojpeg/turbojpeg-sys/target/release/deps --extern libc=/Users/balins/rust-turbojpeg/turbojpeg-sys/target/x86_64-pc-windows-gnu/release/deps/liblibc-305074013371f59d.rmeta -L native=/Users/balins/rust-turbojpeg/turbojpeg-sys/target/x86_64-pc-windows-gnu/release/build/turbojpeg-sys-fc70328649763392/out/lib -l static=turbojpeg-static`
error: could not find native static library `turbojpeg-static`, perhaps an -L flag is missing?

error: could not compile `turbojpeg-sys` (lib) due to 1 previous error

Caused by:
  process didn't exit successfully: `/Users/balins/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc --crate-name turbojpeg_sys --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="cmake"' --cfg 'feature="default"' --cfg 'feature="pkg-config"' --cfg 'feature="require-simd"' -C metadata=f7c1202d12eefe92 -C extra-filename=-f7c1202d12eefe92 --out-dir /Users/balins/rust-turbojpeg/turbojpeg-sys/target/x86_64-pc-windows-gnu/release/deps --target x86_64-pc-windows-gnu -C strip=debuginfo -L dependency=/Users/balins/rust-turbojpeg/turbojpeg-sys/target/x86_64-pc-windows-gnu/release/deps -L dependency=/Users/balins/rust-turbojpeg/turbojpeg-sys/target/release/deps --extern libc=/Users/balins/rust-turbojpeg/turbojpeg-sys/target/x86_64-pc-windows-gnu/release/deps/liblibc-305074013371f59d.rmeta -L native=/Users/balins/rust-turbojpeg/turbojpeg-sys/target/x86_64-pc-windows-gnu/release/build/turbojpeg-sys-fc70328649763392/out/lib -l static=turbojpeg-static` (exit status: 1)
```

I've also tried `cross` to compile my application that depends on `turbojpeg` (it uses Ubuntu 20.04 image), but with the same result:
```
> cross build --target x86_64-pc-windows-gnu
[...]
   Compiling turbojpeg v1.1.0
error: could not find native static library `turbojpeg-static`, perhaps an -L flag is missing?

error: could not compile `turbojpeg-sys` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

On the other hand, compilation works fine when using `windows-2022` GitHub Actions runner, but it uses `x86_64-pc-windows-msvc` toolchain and doesn't need to cross-compile.

**Comment by honzasp** [comment]
Hi, thanks for reporting this issue! I don't have a Windows toolchain at hand, so I can't reproduce the problem at the moment, but I suspect that the issue might be that we use wrong name for the library in the `build.rs` script.

By default, we build the TurboJPEG dependency from source using CMake (via the `cmake` crate). The compiled TurboJPEG artifacts are stored in an "installation directory", which is returned from the call to `cmake.build()` in the build script. We then tell rustc to look for libraries in the `lib` subdirectory of the installation directory using the `cargo:rustc-link-search=native` directive:
https://github.com/honzasp/rust-turbojpeg/blob/5a9f16ded349158a69f40595e0172080e354bbb8/turbojpeg-sys/build.rs#L167-L171

When you run `cargo build` with `--verbose`, you should see the output of the build script. Could you please look into the directory printed by the `cargo:rustc-link-search=native` directive to see whether it contains a static TurboJPEG library, and how is it named? The library is usually named `turbojpeg`, but at least on Windows with the MSVC toolchain, it is named `turbojpeg-static` (see the changes to build.rs in https://github.com/honzasp/rust-turbojpeg/pull/8). I suspect that on Windows with the GNU toolchain, the name might be just `turbojpeg`:
https://github.com/honzasp/rust-turbojpeg/blob/5a9f16ded349158a69f40595e0172080e354bbb8/turbojpeg-sys/build.rs#L172-L179

**Comment by balins** [comment]
Yes indeed :) Thanks for guidance on this. Opened a PR fixing the issue #22
